### ISSUE TITLE
Gather Photos of Boxes and QR Codes Using PiCams

### ISSUE THREAD

**Issue by dragonprevost** [uvic-aero/onboard-computer#12]
We will need lots of sample frames to test with in order generate our Computer Vision Ground Vehicle. This issue requires some members of the team to collect images of 4inch by 4inch by 4inch cardboard boxes using a picamera so we have data to generate features in the autonomous vehicle. 

## Notes
* Make sure to take the photos in various lighting 
* The elevation and angle of the camera will affect how frames are processed
* Take photos at unique distances and try to categorize the images by distance and lighting
* Throw some printed off qr codes on the boxes so we can test out our ability to read qr 
* QR Codes may not be centred on the boxes
* Use different packing tape.

## Conops Details
* codes"The QR codes will be placed on the top and front of the packages, with dimensions of no less than 1 inch, and no greater than 4 inches. "

**Comment by joshuacwnewton** [comment]
Great notes! To add to those notes, here are some additional details from the CONOPS document:

- _"The QR codes will be placed on the top and front of the packages, with dimensions of no less than 1 inch, and no greater than 4 inches. "_
- I don't think there's any guarantee that the QR codes will be centered on the box, too, so that gives some variability for how the QR codes could be attached to the boxes. 
- _"Packing tape does vary in its properties somewhat.  We are not going to tell you the brand or model of the tape. The tape will be hand applied; we’ll try our best to be consistent."_
- _"Packages will [...] have QR code labels on top of the packing tape."_

Might be good to try to cover the ranges in size, placement, tape properties, etc. as well.

**Comment by dragonprevost** [comment]
> Great notes! To add to those notes, here are some additional details from the CONOPS document:
> 
> * _"The QR codes will be placed on the top and front of the packages, with dimensions of no less than 1 inch, and no greater than 4 inches. "_
> * I don't think there's any guarantee that the QR codes will be centered on the box, too, so that gives some variability for how the QR codes could be attached to the boxes.
> * _"Packing tape does vary in its properties somewhat.  We are not going to tell you the brand or model of the tape. The tape will be hand applied; we’ll try our best to be consistent."_
> * _"Packages will [...] have QR code labels on top of the packing tape."_
> 
> Might be good to try to cover the ranges in size, placement, tape properties, etc. as well.

Just made some updated to the description of the issue. Feel free to include any additional factors to the photos when taking them. Just make sure to classify and document the factors.
